issuer-api:
  app:
    profile: default
    logLevel: DEBUG
    basePath: /issuer-api
    internalServerPort: 8080
    mail:
      host: smtp.ionos.de
      port: 587
      username: digitalidentitysupport@dome-marketplace.eu
      existingSecret:
        enabled: true
        name: mail-secret
        key: mail-password
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            ssl:
              trust: smtp.ionos.de
    api:
      externalDomain:
        # if deployed locally set to false
        externalService: true
        scheme: http
        # change by the external url or set to localhost if deployed locally
        host: dome.saas.local
        # internalPort is only used if externalService is false
        internalPort: 80
      path: /
      internalDomain: http://issuer-api:8080
      configSource: yaml
      cacheLifetimeCredentialOffer: 10
      cacheLifetimeVerifiableCredential: 10

    authServer:
      provider: keycloak
      externalDomain:
        # if deployed locally set to false
        externalService: true
        scheme: http
        # change by the external url or set to localhost if deployed locally
        host: localhost
        # internalPort is only used if externalService is false
        internalPort: 8081
        path: /
      internalDomain: http://issuer-keycloak:8080
      realm: CredentialIssuer
      client:
        clientId: oidc4vci-wallet-client
        clientSecret: oidc4vci-wallet-client-secret
        username: user
        existingSecret:
          enabled: true
          name: auth-secret
          clientSecretKey: authServerClientSecret
          clientPasswordKey: authServerClientPassword
      paths:
        tokenPath: /realms/CredentialIssuer/protocol/openid-connect/token
    ui:
      externalDomain:
        # if deployed locally set to false
        externalService: true
        scheme: http
        # change by the external url or set to localhost if deployed locally
        host: localhost
        # internalPort is only used if externalService is false
        internalPort: 4201
        path: /    
      internalDomain: http://wallet-ui:8080

  db:
    host: issuer-postgres
    port: 5432
    externalService: false
    name: issuer
    username: postgres
    existingSecret:
      enabled: true
      name: db-secret
      key: db-password

dome-issuer-keycloak:
  # Keycloak Configuration
  keycloak:
    admin:
      username: admin
      existingSecret:
        enabled: true
        name: keycloak-secrets
        passwordKey: keycloakAdminPassword
    hostname:
      url:
        # if deployed locally set to false
        externalService: true
        scheme: http
        # change by the external url or set to localhost if deployed locally
        host: localhost
        # internalPort is only used if externalService is false
        internalPort: 7001
        path: /
      adminUrl:
        # if deployed locally set to false
        externalService: true
        scheme: http
        # change by the external url or set to localhost if deployed locally
        host: localhost
        # internalPort is only used if externalService is false
        internalPort: 7001
        path: /
    https:
      certificateKeyFile: /opt/keycloak/conf/server.key.pem
      certificateFile: /opt/keycloak/conf/server.crt.pem
      trustStoreFile: /opt/keycloak/conf/truststore.jks
      existingSecret:
        enabled: true
        name: keycloak-secrets
        trustStorePasswordKey: keycloakTrustStorePassword
      clientAuth: request
    db:
      host: issuer-keycloak-postgres
      port: 5432
      externalService: true
      name: cred
      username: postgres
      existingSecret:
        enabled: true
        name: keycloak-secrets
        passwordKey: keycloakDbPassword
      type: postgres

  # Issuer API Configuration
  issuerApi:
    url: http://issuer-api:8080
    externalUrl:
      # if deployed locally set to false
      externalService: true
      scheme: http
      # change by the external url or set to localhost if deployed locally
      host: dome.saas.local
      # internalPort is only used if externalService is false
      internalPort: 80
      path: /

  # Pre-authorization Configuration
  preAuth:
    lifespan: 10
    lifespanTimeUnit: MINUTES

  # Transaction Code Configuration
  txCode:
    size: 4
    description: Enter the PIN code

  # Token Configuration
  token:
    expiration: 2592000

issuer-postgres:
    # -- should the postgresql deployment be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: issuer-postgres
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    nameOverride: issuer-postgres
    ## auth configuration for the database
    auth:
      # -- username to be used
      username: postgres
      # -- should the default postgres user be enabled
      enablePostgresUser: true
      # -- password to be used
      password: postgres
    ## configuration of the postgres primary replica
    primary:
      ## provide db initialization
      initdb:
        ## provide scripts for initialization
        scripts:
          # -- create the database
          create.sh: |
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE issuer;"


issuer-keycloak-postgres:
    # -- should the postgresql deployment be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: issuer-keycloak-postgres
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    nameOverride: issuer-keycloak-postgres
    ## auth configuration for the database
    auth:
      # -- username to be used
      username: postgres
      # -- should the default postgres user be enabled
      enablePostgresUser: true
      # -- password to be used
      password: postgres
    ## configuration of the postgres primary replica
    primary:
      ## provide db initialization
      initdb:
        ## provide scripts for initialization
        scripts:
          # -- create the database
          create.sh: |
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE cred;"