---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: issuer
spec:
  encryptedData:
    keycloak-db-password: AgBHYkV0pMwkyuI6i1me6wo5O/f6oIt36ftlcmwGhG+h+1mhzszkBKL+DYbxKlwGQMGIxOh06MUG4OJMBe/vPD8CQ97tit9zIwGsDo+E4b1410KVdej3M5KuGcrwSMNtR2I0NYqolgOVGlx7kEzmCtpl7ezDJrCbhQQzrHI27Q5dSoS/o8NgVsFeViBGU6trgGCbct78kIrKL0tTkEEqZ/cNLuwWz/aV/6+MLI3l6drfxc+n5Aw6J87FT87VcSyEom8EEID4HCR4+GYp8/wjqNpLBjh7PXoGCifETipQSxYD5gWKoSf4IHFndhEJRULzkdf3tlZ0o0UBalFiChcVLQjSSIfEh1qKwtQLg9nth4CgXJNZh817l9n+TQvJ888L0DW9KKRPAnhsnMIb4nBoQOAXrNwgvpvrT1SyGV8qx93ym7f+uTddTYKmBVk8wdX70LdrzAAw8TD6IhN1FjKCzuZufF9VEqeXcTndYE/S6VZWjC+OCspzSlk+R5w+2qp6OEWYP2uaNUlV6qJZ9YDdXCSexY8RPyOaE1UKiqcZ6/qe9fGG4d/J8JEfhjJNqrEsr9Zo6Xpvkn3J0rHLUaNBQ7tHHst9LGgG+o3uZmgAZCkK92De/mLtyGvJRwnBLUHMEnXRb0jvf6/0VUjBl7kf4pBn5g4BxVANu+yqeobhvoH1CYCNoUPiNDpq1au3TUZIjPTHXyNaNLzeQA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: issuer
