---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-password-secret
  namespace: in2
spec:
  encryptedData:
    keycloak-admin-password: AgApseTD0HaRSzwNvqZXRK5WS7XkfNifHYAa4S4JEG1q8QdqQyyeMT5QrNpKXXRz1amfV5GUro8d2TXdGKDu+C4TRIlUxmsepPkVh0wM97OYHbRK/J7Blh9tVA5yi9vqWP00DOUzvHwxBExtAfY/hlp6RRUJkM6Y5CJlG8g85yv5MsujjQj6rn1MrqAmDAnNv/GlXEry/Lc5okg6JNH5g72AtHbixVi0kU4sDZ/+8wp16um7hWv9TC+V6c+HtaIljaCWkOnp1zAA0JrHKXef7oGHpdVZPNv0Y4xEROccm4wA4/VHkS5vqr6rTOvvY+PBAZ/XrJBPhAaWv4kUQsEEkFBk/4enXv80LiFeY335eGCsZ6CGSGEftUxdAJxpiVIR9aSw7oii7W3ui8lYiYn1SnWkRXdJDT00HG4qyDmtaSEytTBA66zhDQQ+QKi3XHbHHzZlp0O+ZWZfFzPA8o4AfVC8d1535BoGz0v/Z3rHxo55wnGd0XPk65WgOcnR5CM/IPz6OnyXZli/Uq4HEtpseeMSK8LwS2/1LmkrI9M3syX1IpufgrMgzV3C3oyXQxKFnUz2zwSFCBoTO3PbqBfu74SlPuZZSQ4TdUcORLzxgZpYBmA7NBGnJKglIaPpUBIhbflh0+kyjH++DghDhlQyKKMcfFIKc0fi6dK87YhY4DOUEOvB1FzuZjM0IuXaJ6uyI/TvECkTLg==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-password-secret
      namespace: in2
